#!/usr/bin/env python3
"""Generate public/mujoco/conveyor.xml (two driven roller conveyors and a pool of packages) and
src/sim/tasks/conveyor.layout.js (the numbers the task module needs), so scene and task never disagree.
Roller pitch is 3 cm so even the shortest package (8 cm) always rests on two or three rollers; packages on a single
roller seesaw and stall."""
import json
from pathlib import Path

R = 0.014          # roller radius
PITCH = 0.03
BELT_X = 0.305     # belt centre line (robot frame x)
HALF_LEN = 0.12    # roller half length (belt width 0.24)
TOP = 0.79         # belt surface height
ZC = TOP - R
N = 25             # rollers per belt (0.75 m)
SIZES = [(0.06, 0.04, 0.03), (0.075, 0.05, 0.025), (0.04, 0.04, 0.04)]  # package half extents, two of each
IN_Y0, OUT_Y0 = 0.86, -0.14   # first roller of each belt (both run toward -y)
SPAWN_Y = IN_Y0 - 0.03        # packages appear here
EXIT_Y = OUT_Y0 - PITCH * (N - 1) + 0.02  # and are delivered just before they ride off the last roller


def f(x):
    """Format a number without float noise."""
    return f'{x:.4f}'.rstrip('0').rstrip('.')


def belt(name, y0, direction):
    out = [f'    <!-- {name}: {N} driven rollers, surface at z={TOP}, running toward the robot\'s right (-y) -->']
    ya, yb = sorted([y0, y0 + direction * PITCH * (N - 1)])
    L = (yb - ya) / 2 + PITCH / 2
    yc = (ya + yb) / 2
    out.append(f'    <body name="{name}_frame" pos="{BELT_X} 0 0">')
    for sx in (-1, 1):
        out.append(f'      <geom class="touchable" type="box" size="0.012 {L:.3f} 0.035" pos="{sx * (HALF_LEN + 0.015):.3f} {yc:.3f} {ZC + 0.01:.3f}" material="rail"/>')
        for ly in (ya, yb):
            # legs sit under the rails, outside the roller length (rollers must not touch the frame)
            out.append(f'      <geom type="box" size="0.012 0.02 {(ZC - 0.025) / 2:.3f}" pos="{sx * (HALF_LEN + 0.015):.3f} {ly:.3f} {(ZC - 0.025) / 2:.3f}" material="leg"/>')
    out.append('    </body>')
    for i in range(N):
        y = y0 + direction * PITCH * i
        out.append(f'    <body name="{name}_roller{i}" pos="{BELT_X} {y:.3f} {f(ZC)}">')
        out.append(f'      <joint name="{name}_roller{i}" type="hinge" axis="1 0 0" damping="0.001"/>')
        out.append(f'      <geom class="roller" name="{name}_roller{i}"/>')
        out.append('    </body>')
    return out


def motors(name):
    return [f'    <velocity name="{name}_roller{i}" joint="{name}_roller{i}" kv="0.3" ctrlrange="-15 15"/>' for i in range(N)]


pkgs = []
for k, (hx, hy, hz) in enumerate(SIZES):
    for j in range(2):
        n = 2 * k + j
        pkgs.append(f'''    <body name="package{n}" pos="{-3 - 0.3 * n:.1f} 0 {f(hz + 0.001)}">
      <freejoint name="package{n}_free"/>
      <geom name="package{n}" class="touchable" type="box" size="{hx} {hy} {hz}" mass="0.4" condim="4" friction="0.7 0.01 0.0005" material="cardboard"/>
      <geom name="tag{n}" class="label" size="{min(hx, 0.035)} {min(hy, 0.025)} 0.001" pos="0 0 {f(hz + 0.001)}" material="tag"/>
      <geom name="tagbar{n}" class="label" size="{f(min(hx, 0.035) * 0.7)} {f(min(hy, 0.025) * 0.35)} 0.0005" pos="0 0 {f(hz + 0.0025)}" material="tagbar"/>
    </body>''')

xml = f'''<!--
  Conveyor package handling, in the spirit of the humanoid logistics demos: packages arrive on the left belt in
  a random orientation; the operator turns each one so its shipping tag faces up and sets it on the right belt,
  which carries it away. Robot faces +x, +y is the robot's left, z is up.
  Generated by scripts/build-conveyor-scene.py; do not edit by hand.
-->
<mujoco model="g1_conveyor">
  <include file="g1_upper.xml"/>

  <!-- timestep is overridden at load time by the app (?dt=...) -->
  <option timestep="0.002" integrator="implicitfast" cone="elliptic" impratio="10"/>

  <default>
    <default class="touchable">
      <geom solref="0.01 1" priority="1"/>
    </default>
    <default class="roller">
      <geom type="cylinder" size="{R} {HALF_LEN}" quat="0.7071068 0 0.7071068 0" condim="3" friction="0.9 0.005 0.0001" solref="0.01 1" priority="1" material="roller"/>
    </default>
    <default class="label">
      <geom type="box" contype="0" conaffinity="0" density="0"/>
    </default>
  </default>

  <asset>
    <material name="floor" rgba="0.42 0.42 0.44 1"/>
    <material name="roller" rgba="0.3 0.31 0.33 1"/>
    <material name="rail" rgba="0.55 0.57 0.6 1"/>
    <material name="leg" rgba="0.35 0.36 0.38 1"/>
    <material name="stop" rgba="0.85 0.6 0.1 1"/>
    <material name="cardboard" rgba="0.62 0.47 0.3 1"/>
    <material name="tag" rgba="0.95 0.95 0.92 1"/>
    <material name="tagbar" rgba="0.1 0.1 0.1 1"/>
  </asset>

  <worldbody>
    <geom name="floor" type="plane" size="0 0 0.05" material="floor"/>

''' + "\n".join(belt('belt_in', IN_Y0, -1)) + f'''
    <!-- end stop: packages accumulate here in front of the operator -->
    <geom name="stop" class="touchable" type="box" size="0.14 0.01 0.03" pos="{BELT_X} 0.10 {TOP + 0.02}" material="stop"/>

''' + "\n".join(belt('belt_out', OUT_Y0, -1)) + '''

''' + "\n".join(pkgs) + '''
  </worldbody>

  <actuator>
''' + "\n".join(motors('belt_in') + motors('belt_out')) + '''
  </actuator>
</mujoco>
'''
repo = Path(__file__).resolve().parent.parent
out = repo / 'public' / 'mujoco' / 'conveyor.xml'
out.write_text(xml)
layout = {
    'pool': 2 * len(SIZES), 'sizes': SIZES, 'beltX': BELT_X, 'beltTop': TOP, 'rollerRadius': R,
    'spawnY': round(SPAWN_Y, 4), 'exitY': round(EXIT_Y, 4), 'outputStartY': round(OUT_Y0 + 0.02, 4),
}
layout_path = repo / 'src' / 'sim' / 'tasks' / 'conveyor.layout.js'
layout_path.write_text('// Generated by scripts/build-conveyor-scene.py together with public/mujoco/conveyor.xml; do not edit.\n'
                       f'export const LAYOUT = {json.dumps(layout)}\n')
print('wrote', out.name, 'and', layout_path.name, f'({2 * N} rollers, radius {R}, pitch {PITCH})')
