#!/usr/bin/env python3
"""Derive public/mujoco/g1_upper.xml from MuJoCo Menagerie's unitree_g1/g1_with_hands.xml.

Usage: python3 scripts/build-g1-mjcf.py /path/to/mujoco_menagerie/unitree_g1

Changes vs. the Menagerie model (BSD-3, see public/mujoco/LICENSE-g1):
  - fixed base: pelvis freejoint removed (upper-body manipulation, like Isaac's FixedBaseUpperBodyIK task)
  - legs kept as static visuals (joints, collision geoms and actuators removed)
  - gravity compensation on arm + hand bodies (the real arm controller adds a gravity feed-forward)
  - sites: eye (mid360 origin, used for VR calibration), head_cam (d435), {left,right}_palm (IK target),
    {left,right}_grip (center of the grasp, used by task checks)
  - meshdir points at the shared mesh folder (public/models/meshes)
"""
import re
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

LEG = re.compile(r'hip|knee|ankle')
ARM_ROOT = re.compile(r'(left|right)_shoulder_pitch_link')

src_dir = Path(sys.argv[1])
repo = Path(__file__).resolve().parent.parent
out = repo / 'public' / 'mujoco' / 'g1_upper.xml'

tree = ET.parse(src_dir / 'g1_with_hands.xml')
root = tree.getroot()
root.set('model', 'g1_29dof_with_hand_fixed_base')
root.find('compiler').set('meshdir', 'meshes')

for kf in root.findall('keyframe'):
    root.remove(kf)

bodies = {b.get('name'): b for b in root.iter('body')}

# Fixed base
pelvis = bodies['pelvis']
for fj in pelvis.findall('freejoint'):
    pelvis.remove(fj)

# Legs: static visuals only
for name, body in bodies.items():
    if not LEG.search(name):
        continue
    for el in list(body):
        if el.tag in ('joint', 'site') or (el.tag == 'geom' and el.get('class') in ('collision', 'foot')):
            body.remove(el)

leg_joint = re.compile(r'(hip|knee|ankle).*_joint')
for sec in root.findall('actuator') + root.findall('sensor') + root.findall('contact'):
    for el in list(sec):
        if any(leg_joint.search(v) for v in el.attrib.values()):
            sec.remove(el)

# Gravity compensation on both arm subtrees
for name, body in bodies.items():
    if ARM_ROOT.fullmatch(name):
        for b in body.iter('body'):
            b.set('gravcomp', '1')


def site(parent, name, pos, **extra):
    el = ET.SubElement(parent, 'site', {'name': name, 'pos': pos, 'size': '0.005', 'group': '5', **extra})
    return el


torso = bodies['torso_link']
# Origins of mid360_joint / d435_joint relative to torso_link in Unitree's g1 URDF
site(torso, 'eye', '0.0002835 0.00003 0.40618')
site(torso, 'head_cam', '0.0576235 0.01753 0.41987', euler='0 0.8307767 0')

# Palm origin = URDF {side}_hand_palm_joint; grip = between thumb and fingers (fingers curl toward -y on the
# left hand, +y on the right)
site(bodies['left_wrist_yaw_link'], 'left_palm', '0.0415 0.003 0')
site(bodies['right_wrist_yaw_link'], 'right_palm', '0.0415 -0.003 0')
site(bodies['left_wrist_yaw_link'], 'left_grip', '0.115 -0.035 0')
site(bodies['right_wrist_yaw_link'], 'right_grip', '0.115 0.035 0')

ET.indent(tree, space='  ')
out.parent.mkdir(parents=True, exist_ok=True)
header = ('<!-- Generated by scripts/build-g1-mjcf.py from MuJoCo Menagerie unitree_g1/g1_with_hands.xml '
          '(BSD-3-Clause, see LICENSE-g1). Do not edit by hand. -->\n')
out.write_text(header + ET.tostring(root, encoding='unicode') + '\n')

# Meshes that only exist in the Menagerie revision of the model
meshes = repo / 'public' / 'models' / 'meshes'
for m in root.iter('mesh'):
    f = m.get('file')
    if not (meshes / f).exists():
        shutil.copy(src_dir / 'assets' / f, meshes / f)
        print('copied mesh', f)
shutil.copy(src_dir / 'LICENSE', out.parent / 'LICENSE-g1')
print('wrote', out.relative_to(repo))
