// Generated by scripts/build-conveyor-scene.py together with public/mujoco/conveyor.xml; do not edit.
export const LAYOUT = {"pool": 6, "sizes": [[0.06, 0.04, 0.03], [0.075, 0.05, 0.025], [0.04, 0.04, 0.04]], "beltX": 0.305, "beltTop": 0.79, "rollerRadius": 0.014, "spawn": [0.32, 0.9, 1.0307], "plateX": [0.15, 0.55], "plateY": [-0.12, 0.38], "exitY": -0.84, "outputStartY": -0.12}
