// Generated by scripts/build-conveyor-scene.py together with public/mujoco/conveyor.xml; do not edit.
export const LAYOUT = {"pool": 6, "sizes": [[0.06, 0.04, 0.03], [0.075, 0.05, 0.025], [0.04, 0.04, 0.04]], "beltX": 0.305, "beltTop": 0.79, "rollerRadius": 0.014, "spawnY": 0.83, "exitY": -0.84, "outputStartY": -0.12}
